export const Developers: any = [
    {
        id: 1,
        fname: "Dachi",
        lname: "Loseurashvili",
        imgUrl: "../../assets/giorgi.svg",
        description: "Dachi is Web Developer from Georgia",
        info: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo beatae dignissimos provident id delectus veritatis cum odio, magni quis quos fugiat? Ullam iusto, rerum quasi officiis odit perspiciatis mollitia. ",
        university: "International Black Sea Univeristy",
        univIcon: "../../assets/ibsu.png",
        education: "Computer Science",
        proSphere: "Full Stack Web Developer",
        skills: "HTML, CSS, JavaScript, Angular, SASS, NodeJS, MongoDB",
        skill1iconUrl: "../../assets/html.png",
        skill2iconUrl: "../../assets/css.png",
        skill3iconUrl: "../../assets/js.png",
    },

    {
        id: 2,
        fname: "Mariami",
        lname: "Baramidze",
        imgUrl: "../../assets/mariami.svg",
        description: "Mariami is Software Developer from Georgia",
        info: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo beatae dignissimos provident id delectus veritatis cum odio, magni quis quos fugiat? Ullam iusto, rerum quasi officiis odit perspiciatis mollitia. ",
        university: "International Black Sea Univeristy",
        univIcon: "../../assets/ibsu.png",
        education: "Computer Science",
        proSphere: "Software Develper",
        skills: "C++, Java, Python,",
        skill1iconUrl: "../../assets/cpp.png",
        skill2iconUrl: "../../assets/pyth.png",
        skill3iconUrl: "../../assets/java.png",
    },

    {
        id: 3,
        fname: "Ana",
        lname: "Gachechiladze",
        imgUrl: "../../assets/ana.svg",
        description: "Ana is Linux Administrator from Georgia",
        info: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quo beatae dignissimos provident id delectus veritatis cum odio, magni quis quos fugiat? Ullam iusto, rerum quasi officiis odit perspiciatis mollitia. ",
        university: "International Black Sea Univeristy",
        univIcon: "../../assets/ibsu.png",
        education: "Computer Science",
        proSphere: "Linux Administrator",
        skills: "SQL, NTPC, VI-EDITOR, SWITCHES",
        skill1iconUrl: "../../assets/terminal.png",
        skill2iconUrl: "../../assets/linux.png",
        skill3iconUrl: "../../assets/sql.png",
    }
]

